apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    {{- include "hadoop.labels" . | nindent 4 }}
{{- with .Values.nameNode.service.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.nameNode.service.type }}
  ports:
  - name: dfs
    port: {{ .Values.nameNode.port }}
    protocol: TCP
  - name: webhdfs
    port: {{ .Values.nameNode.httpPort }}
  - name: webshdfs
    port: {{ .Values.nameNode.httpsPort }}
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.nameNode.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.nameNode.service.loadBalancerIP }}
  {{- end }}
