{{- if .Values.resourcemanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hadoop.fullname" . }}-resourcemanager-hl
  labels:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    {{- include "hadoop.labels" . | nindent 4 }}
{{- with .Values.resourcemanager.service.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
{{- end }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: 8088
      protocol: TCP
      targetPort: 8088
      name: http
  selector:
    app.kubernetes.io/name: {{ include "hadoop.name" . }}
    app.kubernetes.io/component: namenode
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end}}
